# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('graduation_year', models.PositiveIntegerField()),
                ('current_role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('achievements', models.TextField(blank=True)),
            ],
        ),
    ]
