# Generated by Django 3.1.12 on 2026-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-batch', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='AlumniProfile',
        ),
    ]
