# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('event_name', models.CharField(blank=True, max_length=150)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
            ],
        ),
    ]
