# Generated by Django 3.1.12 on 2026-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('year', models.IntegerField()),
                ('category', models.CharField(default='General', max_length=100)),
            ],
            options={
                'ordering': ['-year', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
