# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_link', models.URLField(blank=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
