# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=150)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
