# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('achieved_on', models.DateField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
