# Generated by Django 3.1.12 on 2026-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('2022-2026', '2022–2026'), ('2023-2027', '2023–2027'), ('2024-2028', '2024–2028'), ('2025-2029', '2025–2029')], max_length=20),
        ),
    ]
