# Generated by Django 3.1.12 on 2026-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_dept', '0002_auto_20260422_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('batch', models.CharField(choices=[('Dec 2021', 'Dec 2021'), ('Jul 2022', 'Jul 2022'), ('Dec 2022', 'Dec 2022'), ('Jul 2023', 'Jul 2023'), ('Dec 2023', 'Dec 2023'), ('Jul 2024', 'Jul 2024'), ('Dec 2024', 'Dec 2024'), ('Jul 2025', 'Jul 2025')], max_length=20)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='phd/profiles/')),
            ],
            options={
                'verbose_name': 'PhD Student',
                'verbose_name_plural': 'PhD Students',
                'ordering': ['batch', 'name'],
            },
        ),
    ]
