# Generated by Django 5.2.12 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('organizer', models.CharField(max_length=150)),
                ('opportunity_type', models.CharField(max_length=80)),
                ('apply_by', models.DateField()),
                ('details', models.TextField()),
            ],
        ),
    ]
